---

authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": "*"
license_file: LICENSE
name: vyos
description: Ansible Network Collection for VYOS devices.
namespace: vyos
readme: README.md
repository: https://github.com/ansible-collections/vyos.vyos
tags: [vyos, networking]
